import type { Metadata } from "next";
import "./globals.css";
import Footer from './_partials/Footer';
import { UserProvider } from "./_utils/AuthProvider";
import Main from './getRefreshToken';

export const metadata: Metadata = {
  title: "DO ME",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <html lang="en">
        <body className=' bg-gray-100' >
          <div className='cont'>
            {children}
          </div>
          <Footer />
          <Main />
        </body>
      </html>
    </UserProvider>

  );
}
